{
 "title": "StaffPulse API Overview",
 "tags": [
  "fastapi",
  "kubernetes",
  "staffpulse"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Request Throughput (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP Latency (P50, P90, P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "HTTP Status Code Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (status)",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Memory Resident Set Size (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"employee-management-system\"}",
     "legendFormat": "Memory Bytes"
    }
   ]
  }
 ]
}